[general] 
import = ["catppuccin-mocha.toml"]

[env]
term = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Maple Mono"
style = "Bold"

[font.bold_italic]
family = "Maple Mono"
style = "Bold Italic"

[font.italic]
family = "Maple Mono"
style = "Italic"

[font.normal]
family = "Maple Mono"
style = "Normal"

[scrolling]
history = 5000

[window]
title = "Alacritty"
class = { instance = "Alacritty", general = "Alacritty" }

[window.padding]
x = 3
y = 6
